spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/budget-app
    username: postgres
    password: xiaominote9
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    username: heroesofbaku@gmail.com
    password: kghoiwsgsundoxjd
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8090
