spring:
  application:
    name: monux
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/budget-app}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:xiaominote9}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    username: heroesofbaku@gmail.com
    password: kghoiwsgsundoxjd
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:liquibase/changelog-master.yml
    drop-first: false
    default-schema: ${MONUX_DB_SCHEMA:public}
    database-change-log-table: MONUX_DBCHANGELOG
    database-change-log-lock-table: MONUX_DBCHANGELOGLOCK


server:
  port: 8090
springfox:
  documentation:
    swagger-ui:
      base-url: /
