create table account
(
    id bigint generated by default as identity
        constraint account_pkey
            primary key,
    account_id varchar(255),
    allow_negative boolean,
    balance numeric(19,2),
    enabled boolean,
    account_name varchar(255),
    show_in_sum boolean
);


create table account_type
(
    id bigint generated by default as identity
        constraint account_type_pkey
            primary key,
    account_type_id varchar(255),
    account_type_name varchar(255)
);

create table app_user
(
    id bigint generated by default as identity
        constraint app_user_pkey
            primary key,
    date_time timestamp,
    full_name varchar(255),
    password varchar(255),
    payment_status varchar(255),
    status varchar(255),
    user_id varchar(255),
    username varchar(255)
);

create table banner
(
    id bigint generated by default as identity
        constraint banner_pkey
            primary key,
    banner_id varchar(255),
    banner_image varchar(255),
    banner_keyword varchar(255),
    banner_text varchar(255),
    banner_title varchar(255)
);

create table blog
(
    id bigint generated by default as identity
        constraint blog_pkey
            primary key,
    blog_id varchar(255),
    blog_creation_date timestamp,
    blog_image varchar(255),
    blog_text varchar(255),
    blog_title varchar(255),
    blog_update_date timestamp
);

create table category
(
    id bigint generated by default as identity
        constraint category_pkey
            primary key,
    category_id varchar(255),
    category_icon varchar(255),
    category_name varchar(255),
    category_type varchar(255)
);

create table currency
(
    id bigint generated by default as identity
        constraint currency_pkey
            primary key,
    currency_id varchar(255),
    currency_name varchar(255)
);

create table definition
(
    id bigint generated by default as identity
        constraint definition_pkey
            primary key,
    definition_id varchar(255),
    definition_icon varchar(255),
    definition_text varchar(255),
    definition_title varchar(255)
);

create table faq
(
    id bigint generated by default as identity
        constraint faq_pkey
            primary key,
    faq_answer varchar(255),
    faq_id varchar(255),
    faq_question varchar(255)
);

create table feature
(
    id bigint generated by default as identity
        constraint feature_pkey
            primary key,
    feature_content varchar(255),
    feature_id varchar(255)
);

create table feedback
(
    id bigint generated by default as identity
        constraint feedback_pkey
            primary key,
    date_time timestamp,
    description varchar(255),
    feedback_id varchar(255),
    status varchar(255)
);

create table label
(
    id bigint generated by default as identity
        constraint label_pkey
            primary key,
    label_id varchar(255),
    label_name varchar(255),
    label_type varchar(255),
    label_visibility boolean
);

create table note
(
    id bigint generated by default as identity
        constraint note_pkey
            primary key,
    description varchar(255),
    note_id varchar(255)
);

create table notification
(
    id bigint generated by default as identity
        constraint notification_pkey
            primary key,
    enabled boolean,
    notification_frequency varchar(255),
    notification_name varchar(255),
    notification_id varchar(255),
    notification_time time
);

create table otp
(
    id bigint generated by default as identity
        constraint otp_pkey
            primary key,
    date_time timestamp,
    otp varchar(255),
    otp_id varchar(255),
    status varchar(255)
);

create table plan
(
    id bigint generated by default as identity
        constraint plan_pkey
            primary key,
    plan_period_type varchar(255),
    plan_id varchar(255),
    plan_price numeric(19,2),
    plan_text varchar(255),
    plan_title varchar(255)
);

create table rel_account_with_account_type
(
    account_type_id bigint
        constraint fkdw0teqryht4qfpatg0tf1o48m
            references account_type,
    account_id bigint not null
        constraint rel_account_with_account_type_pkey
            primary key
        constraint fkdo6sck7hrcgghr6urno5bblb4
            references account
);


create table rel_account_with_currency
(
    currency_id bigint
        constraint fkkiljq7y0a7nfl9vg5wx9lli6m
            references currency,
    acount_id bigint not null
        constraint rel_account_with_currency_pkey
            primary key
        constraint fkb7lrxfcv8bgnvh8m32inp8c7g
            references account
);


create table rel_account_with_user
(
    user_id bigint
        constraint fk8u34ue8c9ykr0fpb8i7bcpsnb
            references app_user,
    account_id bigint not null
        constraint rel_account_with_user_pkey
            primary key
        constraint fk63xmucw1lxttljrffwbkt99hd
            references account
);


create table rel_category_with_user
(
    user_id bigint
        constraint fkx8aufcxqxkyqtrh53u5cedy4
            references app_user,
    category_id bigint not null
        constraint rel_category_with_user_pkey
            primary key
        constraint fki6qoencda0cynhvwkg7rn0wb8
            references category
);


create table rel_feedback_with_user
(
    user_id bigint
        constraint fkgo7cvc13ddbqjanjeqqnhbhei
            references app_user,
    feedback_id bigint not null
        constraint rel_feedback_with_user_pkey
            primary key
        constraint fk9yh85vxv5hddwxh2d4ee0p3su
            references feedback
);


create table rel_label_with_user
(
    user_id bigint
        constraint fkdenvixr05elp6yp43fiw4a27j
            references app_user,
    label_id bigint not null
        constraint rel_label_with_user_pkey
            primary key
        constraint fkagk544hw6blbw32pq9ut8ewg0
            references label
);


create table rel_note_with_user
(
    user_id bigint
        constraint fktmqlixixlhigsfvtjt9nnwgkg
            references app_user,
    note_id bigint not null
        constraint rel_note_with_user_pkey
            primary key
        constraint fkif67ohehjcakqanshttfsea0a
            references note
);


create table rel_notification_with_user
(
    user_id bigint
        constraint fkja18ap9vy89how4f908swdp98
            references app_user,
    notification_id bigint not null
        constraint rel_notification_with_user_pkey
            primary key
        constraint fkluqhbphkhs34yijf2alfnrk31
            references notification
);


create table rel_otp_with_user
(
    user_id bigint
        constraint fkqytalvolrpvqimqui8qob5p29
            references app_user,
    otp_id bigint not null
        constraint rel_otp_with_user_pkey
            primary key
        constraint fkrmebcvv1lnwf8p2sedr4mqg9w
            references otp
);


create table rel_plan_feature
(
    plan_id bigint not null
        constraint fkl8bselkateft5holah7i0xg18
            references plan,
    feature_id bigint not null
        constraint fkkgcom71mvl68ffjych4wc02b8
            references feature
);


create table role
(
    id bigint generated by default as identity
        constraint role_pkey
            primary key,
    role_name varchar(255),
    role_id varchar(255)
);


create table rel_user_role
(
    user_id bigint not null,
    role_id bigint not null
        constraint fk1uxduyl9a5vaa3269v64seye
            references role
);


create table service
(
    id bigint generated by default as identity
        constraint service_pkey
            primary key,
    service_icon varchar(255),
    service_id varchar(255),
    service_text varchar(255),
    service_title varchar(255)
);


create table step
(
    id bigint generated by default as identity
        constraint step_pkey
            primary key,
    step_color varchar(255),
    step_icon varchar(255),
    step_id varchar(255),
    step_text varchar(255),
    step_title varchar(255)
);


create table template
(
    id bigint generated by default as identity
        constraint template_pkey
            primary key,
    amount numeric(19,2),
    date_time timestamp,
    description varchar(255),
    template_id varchar(255),
    transaction_type varchar(255)
);


create table rel_template_with_category
(
    category_id bigint
        constraint fkhtxyby66btulq89mgbro767p0
            references category,
    template_id bigint not null
        constraint rel_template_with_category_pkey
            primary key
        constraint fk21a68dx7r3lrxu4bxu2v5ke1g
            references template
);


create table rel_template_with_label
(
    template_id bigint not null
        constraint fk8r32y5x8l68b8spgbwd4q9944
            references template,
    label_id bigint not null
        constraint fkqstw5dbtc18vnxmiwqgqisy1r
            references label
);


create table rel_template_with_receiver_account
(
    account_id bigint
        constraint fkqt8q011npxsmsrkvyo5jjp7gr
            references account,
    template_id bigint not null
        constraint rel_template_with_receiver_account_pkey
            primary key
        constraint fk91kgfexcnv0sg0rv2hujvefrs
            references template
);


create table rel_template_with_sender_account
(
    account_id bigint
        constraint fklscxdad701831069ba9mif1nu
            references account,
    template_id bigint not null
        constraint rel_template_with_sender_account_pkey
            primary key
        constraint fklhssdj38f0xqp6gm1d72oi4r5
            references template
);


create table rel_template_with_user
(
    user_id bigint
        constraint fkm118o5ctf1uwj1rk3mtkri62o
            references app_user,
    template_id bigint not null
        constraint rel_template_with_user_pkey
            primary key
        constraint fkjanyq2u0ymnm5ib9xfny8dmds
            references template
);


create table transaction
(
    id bigint generated by default as identity
        constraint transaction_pkey
            primary key,
    amount numeric(19,2),
    date_time timestamp,
    description varchar(255),
    transaction_id varchar(255),
    transaction_type varchar(255)
);


create table rel_transaction_with_account_from
(
    account_id bigint
        constraint fkct2eenubl32k2tsldaotqd0st
            references account,
    transaction_id bigint not null
        constraint rel_transaction_with_account_from_pkey
            primary key
        constraint fksvkginkeqi0ttbxuhcqemgdmv
            references transaction
);


create table rel_transaction_with_account_to
(
    account_id bigint
        constraint fk2p9k1oyfw3pjtpco05gi6mlj0
            references account,
    transaction_id bigint not null
        constraint rel_transaction_with_account_to_pkey
            primary key
        constraint fk6p635m502d90908n25eaadbdw
            references transaction
);


create table rel_transaction_with_category
(
    category_id bigint
        constraint fkfw3rff16oeowqac3m9f8w2jou
            references category,
    transaction_id bigint not null
        constraint rel_transaction_with_category_pkey
            primary key
        constraint fkgd1o6xgi9bd7agbsj7gv10jjr
            references transaction
);


create table rel_transaction_with_label
(
    transaction_id bigint not null
        constraint fki3y9paw7x0upn3x3n36pxowwo
            references transaction,
    label_id bigint not null
        constraint fk6hdbb4m76ymh4i37dy6wwv6rr
            references label
);


create table rel_transaction_with_user
(
    user_id bigint
        constraint fk6g3w5e2wp2eo2cikkor3xedic
            references app_user,
    transaction_id bigint not null
        constraint rel_transaction_with_user_pkey
            primary key
        constraint fk2jmdiysblk5mu28t87fgsor27
            references transaction
);


